#!/bin/bash
JAVA_HOME=/opt/jdk/jdk1.6.0_45
ECLIPSE=/opt/eclipse-indigo

set CP=.
CP=$CP:$ECLIPSE/plugins/org.eclipse.equinox.common_3.6.0.v20110523.jar
CP=$CP:$ECLIPSE/plugins/org.eclipse.wst.server.core_1.1.304.v20120208_1420.jar
CP=$CP:$ECLIPSE/plugins/org.jboss.ide.eclipse.as.core_2.3.2.v20130112-0201-H153-Final.jar
CP=$CP:$ECLIPSE/plugins/org.jboss.ide.eclipse.archives.webtools_2.3.2.v20130112-0201-H153-Final.jar
CP=$CP:$ECLIPSE/plugins/org.jboss.ide.eclipse.as.classpath.core_2.3.2.v20130112-0201-H153-Final.jar
CP=$CP:$ECLIPSE/plugins/org.eclipse.core.runtime_3.7.0.v20110110.jar

mkdir classes_as_classpath
mkdir classes_as_core

$JAVA_HOME/bin/javac -d classes_as_classpath -classpath $CP  -sourcepath org.jboss.ide.eclipse.as.core/jbosscore \
  org.jboss.ide.eclipse.as.classpath.core/src/org/jboss/ide/eclipse/as/classpath/core/runtime/CustomRuntimeClasspathModel.java 
  
$JAVA_HOME/bin/javac -d classes_as_core -classpath $CP  -sourcepath org.jboss.ide.eclipse.as.core/jbosscore \
  org.jboss.ide.eclipse.as.core/jbosscore/org/jboss/ide/eclipse/as/core/server/bean/JBossServerType.java

  
  
NOW=$(date +%Y-%m-%d"_"%H.%M.%S)
# backup  
#cp $ECLIPSE/plugins/org.jboss.ide.eclipse.as.classpath.core_2.3.2.v20130112-0201-H153-Final.jar \
#   $ECLIPSE/plugins/org.jboss.ide.eclipse.as.classpath.core_2.3.2.v20130112-0201-H153-Final.jar.bkp-$NOW

echo "Before patch, check date"   
unzip -l $ECLIPSE/plugins/org.jboss.ide.eclipse.as.classpath.core_2.3.2.v20130112-0201-H153-Final.jar | grep 'org/jboss/ide/eclipse/as/classpath/core/runtime/CustomRuntimeClasspathModel'
   
$JAVA_HOME/bin/jar uvf $ECLIPSE/plugins/org.jboss.ide.eclipse.as.classpath.core_2.3.2.v20130112-0201-H153-Final.jar -C classes_as_classpath .

echo "After patch, check date"   
unzip -l $ECLIPSE/plugins/org.jboss.ide.eclipse.as.classpath.core_2.3.2.v20130112-0201-H153-Final.jar | grep 'org/jboss/ide/eclipse/as/classpath/core/runtime/CustomRuntimeClasspathModel'


#cp $ECLIPSE/plugins/org.jboss.ide.eclipse.as.core_2.3.2.v20130112-0201-H153-Final.jar \
#   $ECLIPSE/plugins/org.jboss.ide.eclipse.as.core_2.3.2.v20130112-0201-H153-Final.jar.bkp-$NOW

   
echo "Before patch, check date"   
unzip -l    $ECLIPSE/plugins/org.jboss.ide.eclipse.as.core_2.3.2.v20130112-0201-H153-Final.jar | grep 'org/jboss/ide/eclipse/as/core/server/bean/JBossServerType'
$JAVA_HOME/bin/jar uvf $ECLIPSE/plugins/org.jboss.ide.eclipse.as.core_2.3.2.v20130112-0201-H153-Final.jar -C classes_as_core .

echo "After patch, check date"   
unzip -l    $ECLIPSE/plugins/org.jboss.ide.eclipse.as.core_2.3.2.v20130112-0201-H153-Final.jar | grep 'org/jboss/ide/eclipse/as/core/server/bean/JBossServerType'
