#!/bin/sh

showHelp() {
    cat <<HELP

    $0 <versao do kernel> [-all|-kernel|-modules]

HELP
    exit 0
}
KERNEL_VERSION=$1
OPTION=$2

if [ $1"X" = "X" ] ; then
    echo ""
    echo " - Deve ser passado a versao do kernel"
    echo ""
    showHelp
fi

KERNEL_DIR=/usr/src/linux-$KERNEL_VERSION
if [ ! -d $KERNEL_DIR ] ; then
    echo ""
    echo " - Diretorio $KERNEL_DIR nao encontrado! "
    echo ""
    showHelp
fi
if [ $OPTION"X" = "X" ] ; then
    echo ""
    echo " - Opcao default: -all"
    OPTION="-kernel"
fi
cd $KERNEL_DIR

# backup da configuracao do kernel
X=`date +%Y%m%d"-"%H.%M.%S`
cp .config /root/kernel_config_$KERNEL_VERSION-$X

if [ $OPTION = "-all" ]; then
    make -s -j 3 bzImage &&
    make -s -j 3 modules &&
    make modules_install
elif [ $OPTION = "-kernel" ] ; then
    make -s -j 3 bzImage
elif [ $OPTION = "-modules" ] ; then
    make -s -j 3 modules &&
    make modules_install
else
    echo ""
    echo " - Opcao desconhecida: $2"
    echo ""
    showHelp
fi

#backup do kernel anterior
cd /boot
if [  -e System.map-$KERNEL_VERSION ] ; then
    echo " - copia de seguranca do kernel anterior: "
    echo "   copiando System.map-$KERNEL_VERSION para System.map-$KERNEL_VERSION_$X"
    echo "   copiando vmlinuz-$KERNEL_VERSION para vmlinuz-$KERNEL_VERSION_$X"
    /bin/cp System.map-$KERNEL_VERSION System.map-$KERNEL_VERSION_$X
    /bin/cp vmlinuz-$KERNEL_VERSION vmlinuz-$KERNEL_VERSION_$X
fi
cd -

# atualiza o /boot
echo "#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#"
echo "#_#"
echo "#_#  cp arch/i386/boot/bzImage /boot/vmlinuz-$KERNEL_VERSION "
echo "#_#  cp System.map /boot/System.map-$KERNEL_VERSION "
echo "#_#"
echo "#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#_#"
/bin/cp arch/i386/boot/bzImage /boot/vmlinuz-$KERNEL_VERSION 
/bin/cp System.map /boot/System.map-$KERNEL_VERSION 

cd -


